FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY apps/ ${LAMBDA_TASK_ROOT}/apps/
COPY domains/ ${LAMBDA_TASK_ROOT}/domains/

CMD ["apps.api.lambda_handler.handler"]
